# eslint(静的解析)のバリデーションルール
env:
  es6: true
extends:
  - 'eslint:recommended'
  - plugin:vue/vue3-essential
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Vue: readonly
  axios: readonly
  _const: readonly
  $: readonly
  require: readonly
  global: readonly
  process: readonly
  location: writable
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: "@typescript-eslint/parser"
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  "indent": ["error", 4],
  "keyword-spacing": ["error", { "before": true , "after": true }],
  "quotes": ["error","single"],
  "no-irregular-whitespace": [
    "error",
    {
      skipRegExps: true
    }
  ],
  "@typescript-eslint/no-unused-vars": "error",
  "vue/script-setup-uses-vars": "error",
}
