name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    # defauts:
    #   run:
    #     working-directory: ./back

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: pq
          MYSQL_DATABASE: db_testing
          MYSQL_USER: user
          MYSQL_PASSWORD: pw
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: db_testing
      DB_USERNAME: user
      DB_PASSWORD: pw
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Get Composer Cache Directory
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./back
    - name: Install Dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: ./back
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./back
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./back
    - name: migrate
      run: php artisan migrate
      working-directory: ./back
    - name: frontend build
      run: npm install && npm run dev
      working-directory: ./back
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
      working-directory: ./back
      env:
        APP_ENV: testing
        BCRYPT_ROUNDS: '4'
        MAIL_MAILER: array
        TELESCOPE_ENABLED: false
        QUEUE_CONNECTION: sync
        SESSION_DRIVER: array
